Better error message in font size argument

diff --git a/pnglatex b/pnglatex
--- a/pnglatex
+++ b/pnglatex
@@ -296,7 +296,7 @@ function parse {
                 SIZE=$(echo $OPTARG | sed 's/pt//')
 
                 if ! match $SIZE '^[1-9][0-9]*$'; then
-                    echo "Invalid size." >&2
+                    echo "Invalid font size." >&2
                     exit 1
                 fi
                 ;;
