Bugfixing

diff --git a/pnglatex b/pnglatex
--- a/pnglatex
+++ b/pnglatex
@@ -156,7 +156,7 @@ function parse {
                 MARGIN=$OPTARG
 
                 if [ ! $(echo $MARGIN | egrep '^[0-9]+(x[0-9]+)?$') ]; then
-                    echo "Invalid padding." >&2
+                    echo "Invalid margin." >&2
                     exit 1
                 fi
                 ;;
