Checking padding

diff --git a/pnglatex b/pnglatex
--- a/pnglatex
+++ b/pnglatex
@@ -136,6 +136,11 @@ function parse {
                 ;;
             P)
                 PADDING=$OPTARG
+
+                if [ ! $(echo $PADDING | egrep '^[0-9]+(x[0-9]+)?$') ]; then
+                    echo "Invalid padding." >&2
+                    exit 1
+                fi
                 ;;
             s)
                 SIZE=$OPTARG
